### ISSUE TITLE
Record Linkage example error: dedupe has no attribute console lable

### ISSUE THREAD

**Issue by chrished** [dedupeio/dedupe-examples#108]
`Traceback (most recent call last):
  File "record_linkage_example.py", line 140, in <module>
    dedupe.console_label(linker)
AttributeError: module 'dedupe' has no attribute 'console_label'`

**Comment by jeancochrane** [comment]
What version of dedupe do you have installed? As of 2.0 this method is called [`console_label()`](https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.console_label) but in 1.x it was called `consoleLabel()`, that difference may account for the error.

**Comment by chrished** [comment]
Thanks!

**Comment by Rayku-1** [comment]
I have version 3.0.2 ,I have the same erorr .How to know the proper syntax for my version?

> What version of dedupe do you have installed? As of 2.0 this method is called [`console_label()`](https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.console_label) but in 1.x it was called `consoleLabel()`, that difference may account for the error.
