### ISSUE TITLE
record_linkage_example - Errors after training when saving file

### ISSUE THREAD

**Issue by jameskaris** [dedupeio/dedupe-examples#110]
Using Python 3.7 on Centos 7 workstation.

Run the sample file: record_linkage_example.py

After training first 12 records, press "f" for finished, and the system errors. 

==========================================================================
...
11/10 positive, 1/10 negative
Do these records refer to the same thing?
(y)es / (n)o / (u)nsure / (f)inished / (p)revious
f
Finished labeling
/usr/local/lib/python3.7/site-packages/rlr/crossvalidation.py:122: RuntimeWarning: invalid value encountered in double_scalars
  * (true_distinct + false_distinct)))
Traceback (most recent call last):
  File "/home/administrator/Documents/dedupe-examples-master/record_linkage_example/record_linkage_example.py", line 152, in <module>
    linker.writeSettings(sf)
AttributeError: 'RecordLink' object has no attribute 'writeSettings'

**Comment by jeancochrane** [comment]
Looks like a small typo, the new API for writing settings as of dedupe 2.0 should be `linker.write_settings(sf)`.
