### ISSUE TITLE
Struggling to Get Example Working

### ISSUE THREAD

**Issue by cfindlayvcs** [dedupeio/dedupe-examples#121]
I am doing my best to follow the instructions. The first snag I hit is this line:

`mkvirtualenv dedupe-examples`

I think this should be:

`virtualenv dedupe-examples`

Is that correct? `mkvirtualenv ` doesn't seem to exist

Running `pip install -r requirements.txt` just results in a bunch of errors:

![image](https://user-images.githubusercontent.com/73087164/119435341-46101780-bd5d-11eb-93a1-f7b579520773.png)

Is this a problem with my environment?

**Comment by cfindlayvcs** [comment]
I got a little further

![image](https://user-images.githubusercontent.com/73087164/119447609-7ebaeb80-bd73-11eb-86f6-6912e12b6498.png)

**Comment by fgregg** [comment]
yes. this looks like the problem: https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe
