### ISSUE TITLE
error running csv_example : SystemError: Negative size passed to PyString_FromStringAndSize

### ISSUE THREAD

**Issue by motrippy** [dedupeio/dedupe-examples#54]
Hello!

I'm new to python and just following the readme as well as an article that referenced dedupeio http://blog.districtdatalabs.com/basics-of-entity-resolution.

I'm unable to complete running csv_example.py due to the ff error:

```
15/10 positive, 14/10 negative
Do these records refer to the same thing?
(y)es / (n)o / (u)nsure / (f)inished / (p)revious
f
Finished labeling
Traceback (most recent call last):
  File "csv_example.py", line 151, in <module>
    threshold = deduper.threshold(data_d, recall_weight=1)
  File "/Users/mo-manguiat/Projects/dedupetest/env/lib/python3.5/site-packages/dedupe/api.py", line 237, in threshold
    return self.thresholdBlocks(blocked_pairs, recall_weight)
  File "/Users/mo-manguiat/Projects/dedupetest/env/lib/python3.5/site-packages/dedupe/api.py", line 68, in thresholdBlocks
    probability = core.scoreDuplicates(self._blockedPairs(blocks),
  File "/Users/mo-manguiat/Projects/dedupetest/env/lib/python3.5/site-packages/dedupe/api.py", line 248, in _blockedPairs
    block, blocks = core.peek(blocks)
  File "/Users/mo-manguiat/Projects/dedupetest/env/lib/python3.5/site-packages/dedupe/core.py", line 278, in peek
    record = next(records)
  File "/Users/mo-manguiat/Projects/dedupetest/env/lib/python3.5/site-packages/dedupe/api.py", line 281, in _blockData
    for block in viewvalues(blocks):
  File "/Users/mo-manguiat/Projects/dedupetest/env/lib/python3.5/_collections_abc.py", line 693, in __iter__
    for key in self._mapping:
  File "/Users/mo-manguiat/anaconda/lib/python3.5/shelve.py", line 95, in __iter__
    for k in self.dict.keys(): 
SystemError: Negative size passed to PyBytes_FromStringAndSize
```

I'm using the ff in a virtual environment:
Python 3.5.2
dedupe  1.6.10
future 0.16.0
Unidecode 0.4.16
numpy 1.12.1

Mac OSX 10.11.4
memory 16 GB 1867 MHz DDR3
free storage space at 40GB (might this be the problem?)

Googling the error led me to a few posts on stackoverflow about perhaps storage or memory limits, but no clear solutions yet.  Also, the csv file isn't large so i'm not sure how to proceed.

I also got the same error running it on a python 2.7 virtual environment

any help would be appreciated :) thanks!

**Comment by fgregg** [comment]
Sorry to hear this. What is "ff"?

Could you.

1. paste the output of this (running python3)
```python
import shelve
d = shelve.open('f')
import dbm
print(dbm.whichdb('f'))
```

2. try to install dedupe outside of anaconda and let me know if you still have the problem

**Comment by motrippy** [comment]
Hello,

Thanks for the reply!
Sorry 'ff' is just an abbreviation for 'following' so i meant "the following error" :) 

Here's what i got with your suggestions:

1. ran on terminal
```
Mas-MacBook-Pro:~ mo-manguiat$ python
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shelve
>>> d = shelve.open('f')
>>> import dbm
>>> print(dbm.whichdb('f'))
dbm.ndbm
```

2. unfortunately i ran into another error trying to install dedupe on my Mac's default python (/usr/bin/python) 

```
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Version
s/2.7/include/python2.7/persistent'
```
i tried solution here http://stackoverflow.com/questions/31900008/oserror-errno-1-operation-not-permitted-when-installing-scrapy-in-osx-10-11 but still got the same error :(

I'm afraid I'm still stuck :-P

**Comment by fgregg** [comment]
could you clone https://github.com/dedupeio/dedupe and then `dedupe` library run 

`python tests/canonical.py`

and let me know if you get the same error?

**Comment by tendres** [comment]
I too am seeing the same error:
```
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_collections_abc.py", line 693, in __iter__
    for key in self._mapping:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shelve.py", line 95, in __iter__
    for k in self.dict.keys():
SystemError: Negative size passed to PyBytes_FromStringAndSize

```
```
import shelve
d = shelve.open('f')
import dbm
print(dbm.whichdb('f'))
```
returns 
`dbm.ndbm`


`python tests/canonical.py`  runs successfully (exit code 0).

**Comment by jmsmcniff** [comment]
Same error here too:

`import shelve
d = shelve.open('f')
import dbm
print(dbm.whichdb('f'))`

returns: "None"

tests/canonical.py succeeds.

**Comment by fgregg** [comment]
hrmm... 

can folks please share their `csv_example_learned_settings` file along with output of `which python`

**Comment by fgregg** [comment]
I think this has been resolved.
