### ISSUE TITLE
error importing dedupe in csv example: "cannot import name 'LBFGSError'"

### ISSUE THREAD

**Issue by wkniffin** [dedupeio/dedupe-examples#59]
Hello!
I am getting an error when I try to import dedupe with a simple: 
`import dedupe`

I am running my python with anaconda3 in a python 3.5 environment on Windows.
The error verbatim is: ImportError: cannot import name 'LBFGSError'

I didn't think that dedupe had any errors while installing via pip.

The error occurs in the file "__init__.py" in the lbfgs folder. The code is as follows:
```python
"""
LBFGS and OWL-QN optimization algorithms

Python wrapper around liblbfgs.
"""

from ._lowlevel import LBFGS, LBFGSError


def fmin_lbfgs(f, x0, progress=None, args=()):
    """Minimize a function using LBFGS or OWL-QN.

    See LBFGS.minimize for full documentation.
    """
    return LBFGS().minimize(f, x0, progress=progress, args=args)
```
Thanks for any help you can provide!

**Comment by fgregg** [comment]
I'm sorry, I can't support anaconda.
