### ISSUE TITLE
module 'dedupe' has no attribute 'backport'

### ISSUE THREAD

**Issue by jbb352** [dedupeio/dedupe-examples#60]
I'm getting the above error when running the mysql_example.  I followed the readme file as follows

Installed MYSQL - 5.7.18
updated the mysql.cnf with the username and pass
ran `pip install -r requirements.txt`

initialised the db `python mysql_init_db.py` had to make an edit from one of the other issues `c.execute("SET sql_mode = ''")`

Then ran `python mysql_example.py` and get the error

Traceback (most recent call last):
  File "mysql_example.py", line 217, in <module>
    pool = dedupe.backport.Pool(processes=2)
AttributeError: module 'dedupe' has no attribute 'backport'

I'm running the package on Ubuntu 16.04 and using Python 3.6

Am I missing some dependency?

**Comment by fgregg** [comment]
what version of dedupe do you have installed?
