### ISSUE TITLE
mysql_example error UnicodeEncodeError

### ISSUE THREAD

**Issue by sarthakchakravarty** [dedupeio/dedupe-examples#66]
I am facing an issue while running mysql_example.py on campaign dataset.
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4: ordinal not in range(128)
Python version: 2.7.12
![screenshot-2017-10-24 screenshot from 2017-10-24 13-48-59 png png image 1366 x 768 pixels - scaled 87](https://user-images.githubusercontent.com/31059970/31933018-8b2bb522-b8c5-11e7-9af6-5d7fa8e24ca4.png)

**Comment by sarthakchakravarty** [comment]
I think this a version issue. The error is not coming up while running the code in python3.

**Comment by sarthakchakravarty** [comment]
But I am getting a new error now..
ValueError: No records have been blocked together. Is the data you are trying to match like the data you trained on?
stack trace is..
`INFO:root:creating block_key index
INFO:root:calculating plural_block
INFO:root:adding donor_id index and sorting index
INFO:root:creating covered_blocks
INFO:root:creating smaller_coverage
clustering...
Traceback (most recent call last):
  File "mysql_example.py", line 368, in <module>
    threshold=0.5)
  File "/home/formcept/.local/lib/python3.5/site-packages/dedupe/api.py", line 116, in matchBlocks
    threshold=0)
  File "/home/formcept/.local/lib/python3.5/site-packages/dedupe/core.py", line 213, in scoreDuplicates
    raise ValueError("No records have been blocked together. "
ValueError: No records have been blocked together. Is the data you are trying to match like the data you trained on?`

**Comment by abhishekchotaliya** [comment]
Adding following lines after `from __future__ import print_function` will solve the problem.

```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by fgregg** [comment]
I think I've addressed all these issues in https://github.com/dedupeio/dedupe-examples/commit/8eebb494937cc9ff93a10404128715330c122aec 

If I haven't please re-open this issue. Thanks!
