### ISSUE TITLE
ValueError: need more than 0 values to unpack in gazetteer_example.py

### ISSUE THREAD

**Issue by alixaxel** [dedupeio/dedupe-examples#70]
I can't run `gazetteer_example` on Ubuntu:

```shell
$ python gazetteer_example.py
importing data ...
gazetteer_example.py:53: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.
  column = unidecode(column)
N data 1 records: 1081
N data 2 records: 1092
/home/alix/.local/lib/python2.7/site-packages/dedupe/sampling.py:39: UserWarning: 7500 blocked samples were requested, but only able to sample 7498
  % (sample_size, len(blocked_sample)))
starting active labeling...
# labeling...
Finished labeling
Start calculating threshold
Threshold: 0.148433491588
Traceback (most recent call last):
  File "gazetteer_example.py", line 165, in <module>
    results = gazetteer.match(messy, threshold=threshold, n_matches=1)
  File "/home/alix/.local/lib/python2.7/site-packages/dedupe/api.py", line 992, in match
    return list(clusters)
  File "/home/alix/.local/lib/python2.7/site-packages/dedupe/clustering.py", line 200, in gazetteMatching
    for block in scored_blocks:
  File "/home/alix/.local/lib/python2.7/site-packages/dedupe/core.py", line 345, in scoreGazette
    for scored_pairs in imap(score_records, records):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
ValueError: need more than 0 values to unpack
```

**Comment by victorbergelin** [comment]
I have the same issue

**Comment by fgregg** [comment]
This should be addressed with the newest release of dedupe. 1.9.0

**Comment by jvanhees** [comment]
I'm still running into this issue, Dedupe version 1.9.1, running on Google App Engine Flex. Any idea where this is coming from and if I can do something myself to fix it?

**Comment by mehrrsaa** [comment]
I am running into this issue too. Any help on what the reason could be and how to fix would be appreciated. For me this only happens when trying out gazetteer.

**Comment by fgregg** [comment]
Thanks for the report. This ended up being about a subtle difference between how multiprocessing works in python 2 and python3. This issue should now be really address in dedupe 1.9.2

**Comment by mehrrsaa** [comment]
Thanks for the quick response! When is 1.9.2 due to release? Is it something I could fix if you point me to its direction (assuming I know a bit about multiprocessing in python)?

**Comment by fgregg** [comment]
It's available right now.

`pip install dedupe==1.9.2`

**Comment by mehrrsaa** [comment]
thanks so much! for some reason pip upgrade did not get this
