### ISSUE TITLE
syntax error at or near ":"

### ISSUE THREAD

**Issue by wedwardbeck** [dedupeio/dedupe-examples#73]
Hello,
I'm getting a syntax issue at line 279 of the example.py with the ":" 

https://github.com/dedupeio/dedupe-examples/blob/46856774a3287810ccb64e6976ef9137ccbae59c/pgsql_big_dedupe_example/pgsql_big_dedupe_example.py#L279

I'm getting this syntax issue:
-----
Traceback (most recent call last):
  File "vn_data_process.py", line 258, in <module>
    c.execute("CREATE TABLE smaller_coverage "
  File "/home/felix/Env/dedupe/lib/python3.5/site-packages/psycopg2/extras.py", line 249, in execute
    return super(RealDictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: syntax error at or near ":"
LINE 1: ...erage AS (SELECT vendor_id, block_id,  sorted_ids[:(idx(sort...

I've come across one post on StackOverflow on this colon, and can run with it removed.  But then I hit another error at:

https://github.com/dedupeio/dedupe-examples/blob/46856774a3287810ccb64e6976ef9137ccbae59c/pgsql_big_dedupe_example/pgsql_big_dedupe_example.py#L311

Subsequent error if colon removed:
-----
clustering...
Traceback (most recent call last):
  File "vn_data_process.py", line 317, in <module>
    clustered_dupes = list(clustered_dupes)
  File "/home/felix/Env/dedupe/lib/python3.5/site-packages/dedupe/api.py", line 121, in matchBlocks
    threshold=0)
  File "/home/felix/Env/dedupe/lib/python3.5/site-packages/dedupe/core.py", line 229, in scoreDuplicates
    fillQueue(record_pairs_queue, records, n_map_processes)
  File "/home/felix/Env/dedupe/lib/python3.5/site-packages/dedupe/core.py", line 261, in fillQueue
    chunk = tuple(itertools.islice(iterable, int(chunk_size)))
  File "/home/felix/Env/dedupe/lib/python3.5/site-packages/dedupe/api.py", line 260, in <genexpr>
    pairs = (combinations(sorted(block), 2) for block in blocks)
  File "vn_data_process.py", line 292, in candidates_gen
    smaller_ids = lset(smaller_ids)
TypeError: 'int' object is not iterable   

It looks like this was added in 380555c on March 14, 2017.  I'm not sure how to proceed with that colon - or how to verify what could be missing on my server.   I'm running Ubuntu 16.04 on Digital Ocean, and have installed requirements.  Should that colon be retained?  Am I somehow not providing a variable (can't find reference to that)?  
thanks

**Comment by BobFonix** [comment]
The ":(idx" issue is caused by a missing extension is postgres.

You can fix it by creating an extension in your scheme:

CREATE EXTENSION intarray;

Not sure about the second issue thou..

**Comment by wedwardbeck** [comment]
Thanks for replying.  However intarray is already enabled, and I'm still getting that syntax error on the colon.  
PSQL 9.5.12
Python 3.5.2

So am wondering what could be the difference in my environment.  I've been trying to find an alternate process for that code, but am not yet strong enough in Python to get there.  I've also tried reverting to a prior version, but run into other errors.

**Comment by BobFonix** [comment]
Maybe try python 2.7 in a new virtualenv? Should be quick to set up. I had compatibility issues before in py3, howeverI know the scripts were updates to py3 compatible.

**Comment by wedwardbeck** [comment]
OK - will try that.  Thanks for the advice!

**Comment by sontata** [comment]
Have you solved this problem?

**Comment by aKumpan** [comment]
Same issue for me,

```psycopg2.ProgrammingError: function idx(integer[], integer) does not exist
LINE 1: ...age AS (SELECT donor_id, block_id,  sorted_ids[0:(idx(sorted...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.```

@wedwardbeck did you resolve this?

**Comment by aKumpan** [comment]
Fixed with adding 
`c.execute("CREATE EXTENSION intarray")`

after it, this code worked:
`c.execute("CREATE TABLE smaller_coverage "
          "AS (SELECT donor_id, block_id, "
          " sorted_ids[:(idx(sorted_ids, block_id) - 1)]"
          "      AS smaller_ids "
          " FROM plural_block INNER JOIN covered_blocks "
          " USING (donor_id))")`

**Comment by fgregg** [comment]
We address this in https://github.com/dedupeio/dedupe-examples/blob/master/pgsql_big_dedupe_example/README.md
