### ISSUE TITLE
LOOKING FOR A CLEAR FIX : UserWarning: NumPy linked against 'Accelerate.framework'

### ISSUE THREAD

**Issue by mehrrsaa** [dedupeio/dedupe-examples#74]
Hi all, 

I am using dedupe to obtain a threshold for matches, running the following code, it fails to use multiprocessing:

threshold = deduper.threshold(full_dict, recall_weight=1)
(full_dict is my data)

The warning I get is:
**UserWarning: NumPy linked against 'Accelerate.framework'. Multiprocessing will be disabled. http://mail.scipy.org/pipermail/numpy-discussion/2012-August/063589.html
  warnings.warn("NumPy linked against 'Accelerate.framework'. "**

not using multiprocessing it is painfully slow.  I am testing this on jupyter notebook with anaconda2 on mac. I know it would probably work if I switch to a linux server and not use anaconda but I was wondering if there is a fix for this anyway. There is no clear answer online that actually fixes this.

Thank you.

**Comment by fgregg** [comment]
These instructions worked as of a few years ago:
https://dedupe.readthedocs.io/en/latest/OSX-Install-Notes.html

I don't know if they are still current. Please update this issue if you end
up succeeding at solving this.

In case you don't know, it is an internet convention that writing in ALL
CAPS means shouting, and so is considered rude.

**Comment by mehrrsaa** [comment]
sorry absolutely did not mean to shout. I thought it means excitement or to grab attention if used to communicate with strangers because why would I want to shout at anyone I do not know? :) 

Thanks for the info. Will update if I arrive at a current and better solution.

**Comment by mehrrsaa** [comment]
PS. I really really do appreciate the work of the authors of this package, so thank you so much for teh hard work. It is truly amazing. Hope I can make it work faster on large datasets with the multithreading enabled.

**Comment by fgregg** [comment]
you are welcome, I hope you can get it working for you.
