### ISSUE TITLE
Clarifying the use of original_length in the Sample function and reusing the trained model

### ISSUE THREAD

**Issue by mehrrsaa** [dedupeio/dedupe-examples#77]
Hi all,

As mentioned and explained in documents and other issues, we can perform the training on a random sample of the data (and provide the original length of the sample), and then we could load the saved settings and perform dedupe/gazetteer on the original data.

My question is: assume for gazetteer, we have a canonical set of N rows and we want to match data of M rows to it. But we don't want to train every time for a new similar dataset, or when new rows are added to my data. Considering the original lengths I provided, what are the potential drawbacks of using the model on different size (but similar) datasets? If any drawbacks, is there a solution?

Thank you.

**Comment by fgregg** [comment]
Hi @mehrrsaa, please ask usage questions about dedupe on https://stackoverflow.com/ 

if you run into bugs in the dedupe-examples code please file them here.

Thanks!

**Comment by mehrrsaa** [comment]
Done. Thank you!
(https://stackoverflow.com/questions/49823386/clarifying-the-use-of-original-length-in-the-sample-function-and-reusing-the-tra)
