### ISSUE TITLE
MySQL: plural_key.block_key column is empty, extra column added.

### ISSUE THREAD

**Issue by jbeales** [dedupeio/dedupe-examples#83]
In the MySQL demo, the `block_key` column in the `plural_key` table is always empty, but a new column is added: `MIN(block_key)`. This is because When using `CREATE TABLE ... SELECT` MySQL "MySQL creates new columns for all elements in the SELECT." [link](https://dev.mysql.com/doc/refman/5.5/en/create-table-select.html). If we give the columns in the SELECT a name that is already in the CREATE TABLE statement then a new column isn't created, but values are inserted into the existing column.

**Comment by jbeales** [comment]
Yes. I was working on a PR but ran into another bug in the same query - the
key used for the join is not the same collation in each table, and MySQL
doesn’t seem to like that, so I think that either the collation will have
to be removed from the Create statement for the raw_data table or one will
have to be added to the Create statements for the rest of the tables.

**Comment by fgregg** [comment]
Boy MySQL has changed a lot in the last 5 or so years.

**Comment by sontata** [comment]
I write about this: https://github.com/dedupeio/dedupe-examples/issues/75
You should to use:
СREATE TABLE plural_key
(
block_key VARCHAR(200),
block_id INTEGER UNSIGNED AUTO_INCREMENT,
PRIMARY KEY (block_id)
)
(SELECT MIN(block_key) as block_key
FROM
(SELECT
block_key,
GROUP_CONCAT(donor_id ORDER BY donor_id) AS block
FROM blocking_map
GROUP BY block_key
HAVING COUNT(*) > 1) AS blocks
GROUP BY block);

**Comment by bespin1** [comment]
I had the same issue in mysql_example.py and was getting this message:

`"No records have been blocked together. Is the data you are trying to match like the data you trained on?"`

Just wanted to confirm that naming the field as described worked for me as well.

`MIN(block_key) as block_key`
