### ISSUE TITLE
Getting limited clusters and few records missed out while scoring

### ISSUE THREAD

**Issue by bharathts1507** [dedupeio/dedupe-examples#94]
Hi, I m using dedupe (version 1.6.5 in windows) to identify duplicate records in a data. I am loading trained model and scoring on new set of data of 20000 records. I know there are 10000 duplicates in it. But the model is throwing only 6000 clusters which is 12000 records only. The remaining records are not getting mapped to any clusters even though they have duplicates. Please suggest a solution

**Comment by fgregg** [comment]
not enough to detail
